{
	"pwd": "admin", 
	"sid": "bad_motherfucker",  
	"sys_signalStrength": "", 
	"sys_networkName": "",
	"sys_iccid": "",
	"sys_imsi": "",
	"total_send": "0",
	"total_recv": "0",
	"data_threshold_resetDay": "1",
	"data_threshold_value": "10",
	"data_threshold_status": "0",
	"language": "en",
	"wifi_band": "5GHz",
	"wifi_status": 1,
	"wifi_bandwidthMode": 2,
	"wifi_channel": 6,
	"wifi_apIsolation": 1,
	"wifi_security": "wpa2/wpa",
	"wifi_mode": "n",
	"wifi_hideSSID": 0,
	"wifi_SSIDName": "myfancyriserver",
	"wifi_password": "qqwwwwqq",
	"wifi_5G_bandwidthMode": "20MHz",
	"wifi_5G_channel": 36,
	"wifi_5G_security": "wpa2/wpa",
	"wifi_5G_mode": "ac",
	"_": "_"
}