#!/bin/sh

do_start() {
      connmanctl enable wifi
      connmanctl apmanager disable wlan0
      connmanctl apmanager set wlan0 SSID cm31_wifi
      connmanctl apmanager set wlan0 Mode n
      connmanctl apmanager set wlan0 Passphrase 12345678
      connmanctl apmanager enable wlan0
}

do_stop() {
      # start-stop-daemon --stop --name cm31_api --quiet
      echo "i am not do_stop"
}

case "$1" in
start)
      echo "Starting $DESC"
      do_start
      ;;
stop)
      echo "Stopping $DESC"
      do_stop
      ;;
restart | force-reload)
      echo "Restarting $DESC"
      do_stop
      sleep 1
      do_start
      ;;
*)
      echo "Usage: $0 {start|stop|restart|force-reload}" >&2
      exit 1
      ;;
esac

exit 0
